### PR TITLE
Fix Error: strconv.Atoi: parsing "": invalid syntax

### LINKED ISSUE #223: Error: strconv.Atoi: parsing "": invalid syntax
### Terraform Version
Terraform v0.12.5

### Heroku Provider Version
Run `terraform -v` to show core and any provider versions. A sample output could be:

```
Terraform v0.12.5
+ provider.heroku v2.1.0
```

### Affected Resource(s)
???

### Terraform Configuration Files
```hcl
resource "heroku_app" "greenroom" {
  name   = "tracer-greenroom"
  region = "virginia"
  space  = "tracer-production"

  organization {
    name = "tracer-ops"
  }

  stack = "heroku-18"
}

resource "heroku_addon" "greenroom_graphite" {
  app  = "${heroku_app.greenroom.name}"
  plan = "hostedgraphite:small"
}
```

### Debug Output
https://gist.github.com/James-Quigley/40e33125f05fb3d57474b63d3109e14e

### Expected Behavior
Successfully ran `plan` or at least said what was invalid

### Actual Behavior
``Error: strconv.Atoi: parsing "": invalid syntax`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan -input=false`

### Important Factoids
Pretty sure this has to do with the 2.1.0 release. Downgrading to 2.0.3 is fine

### PR DESCRIPTION
**Pull request by davidji99**
Resolves #223

### CODE REVIEW

**Comment by davidji99** [comment]
Changing up the migration logic a bit where the `if` statement will just look for `config.#` as that is set in the statefile when `heroku_addon.config` is present in the configuration file. If the `heroku_addon.config` is not set, then the migration will essentially be skipped.

`DEBUG` output when migration is run:
```
2019-08-06T14:26:12.468+0900 [DEBUG] plugin.terraform-provider-heroku: 2019/08/06 14:26:12 Checking if heroku_addon.config in state is in the old TypeList of TypeSet format
2019-08-06T14:26:12.468+0900 [DEBUG] plugin.terraform-provider-heroku: 2019/08/06 14:26:12 heroku_addon.config is not the correct data type. Migrating to a TypeList of TypeSet to TypeSet.
2019-08-06T14:26:12.468+0900 [DEBUG] plugin.terraform-provider-heroku: 2019/08/06 14:26:12 Migrated heroku_addon.config attribute from TypeList of TypeSet to TypeSet.
`

`DEBUG` output when migration is not run:
```
2019-08-06T14:23:41.414+0900 [DEBUG] plugin.terraform-provider-heroku: 2019/08/06 14:23:41 Checking if heroku_addon.config in state is in the old TypeList of TypeSet format
2019-08-06T14:23:41.414+0900 [DEBUG] plugin.terraform-provider-heroku: 2019/08/06 14:23:41 heroku_addon.config is the correct data type. No migration needed.
```
^ The above happens when `heroku_addon.config` is not set

File: heroku/resource_heroku_addon_migrate.go [hunk 1]
```diff
@@ -59,69 +59,67 @@ func migrateAddonIdsStateV0toV1(is *terraform.InstanceState, client *heroku.Serv
...
-		// This means the config attribute is the correct data type of just a TypeSet.
-		log.Printf("heroku_addon.config is the correct data type. No migration needed.")
-		return is, nil
-	}
-
-	// If the execution has gotten this far, this means the config attribute is a TypeList of TypeSets,
-	// which means we migrate it to just a TypeSet.
-	log.Printf("heroku_addon.config is not the correct data type. Migrating to a TypeList of TypeSet to TypeSet.")
+	log.Printf("Checking if heroku_addon.config in state is in the old TypeList of TypeSet format")
+	if is.Attributes["config.#"] != "" {
```
Comment (davidji99) [inline heroku/resource_heroku_addon_migrate.go]: Checking if `config.#` exist is the only way I know of to detect that `heroku_addon.config` is in the statefile pre v0.12. If there's a better idea, I'm all ears!

**Comment by davidji99** [comment]
Hi @mars, review? Thanks!
